### PR TITLE
Code cleanup. Parameter encoding.

### PR DESCRIPTION
**Pull request by naithar**
Readme update for current library usage. Made typealias for parameter type. 
Added `Encoding` protocol for parameter encoding.
## Motivation and Context

Code cleanup mostly.
Moved parameter encoding to protocol and structs extending that protocol.
## How Has This Been Tested?

Tested on linux and mac os
## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by naithar** [comment]
@rob-deans is there any reason for parameter type being an Array of Dictionaries?
And wouldn't it be better to move parameter encoding to protocol and make extensions for URL, JSON and Multipart? I can do it this PR.

**Comment by rob-deans** [comment]
The reason was dictionaries don't keep their order and as a result the testing was inconsistent with regards to adding parameters to the url, but if there are other ways we're all ears.
That probably be a better way of approaching this.

**Comment by naithar** [comment]
Wouldn't the use of `.contains` method solve this problem, since it's only testing issue? There're hardly any HTTP request that depends on parameters order.

**Comment by rob-deans** [comment]
Thanks for the changes, I'll merge now, I'll have a look at the array of dictionaries problem

**Pull request merged**
