### PR TITLE
Fix Linux compilation error

### PR DESCRIPTION
**Pull request by mattcolegate**
When compiling on Linux (Ubuntu 14.04, Swift 3.0.2) I ran into the following compilation error:

Compile Swift Module 'KituraRequest' (15 sources)
/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/BodyPart+MimeTypeSubtypes.swift:17:20: error: 'MimeType' is not a member type of 'BodyPart'
extension BodyPart.MimeType {
~ ^

I looked at the generated yaml:

"<KituraRequest.module>":
tool: swift-compiler
executable: "/home/matthew/swift-3.0.2-RELEASE-ubuntu14.04/usr/bin/swiftc"
module-name: "KituraRequest"
module-output-path: "/home/matthew/bluemix/.build/debug/KituraRequest.swiftmodule"
inputs: ["<LoggerAPI.module>","<Socket.module>","<CCurl.module>","<OpenSSL.module>","<SSLService.module>","<CEpoll.module>","<CHTTPParser.dylib>","<KituraNet.module>"]
outputs: ["<KituraRequest.module>","/home/matthew/bluemix/.build/debug/KituraRequest.build/KituraRequest+Error.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/KituraRequest.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/URLEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/Encoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/JSONEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+Parameters.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+Method.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+CompletionHandler.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart+MimeTypeSubtypes.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyBoundary.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart+MimeType.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/KituraRequest+Random.swift.o"]
import-paths: ["/home/matthew/bluemix/.build/debug"]
temps-path: "/home/matthew/bluemix/.build/debug/KituraRequest.build"
objects: ["/home/matthew/bluemix/.build/debug/KituraRequest.build/KituraRequest+Error.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/KituraRequest.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/URLEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/Encoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/JSONEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartEncoding.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+Parameters.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+Method.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Request/Request+CompletionHandler.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart+MimeTypeSubtypes.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyBoundary.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/BodyPart+MimeType.swift.o","/home/matthew/bluemix/.build/debug/KituraRequest.build/Encoding/MultipartFormData/KituraRequest+Random.swift.o"]
other-args: ["-j8","-D","SWIFT_PACKAGE","-Onone","-g","-enable-testing","-Xcc","-fmodule-map-file=/home/matthew/bluemix/Packages/CCurl-0.2.3/module.modulemap","-Xcc","-fmodule-map-file=/home/matthew/bluemix/Packages/OpenSSL-0.3.1/module.modulemap","-Xcc","-fmodule-map-file=/home/matthew/bluemix/Packages/CEpoll-0.1.0/module.modulemap","-Xcc","-fmodule-map-file=/home/matthew/bluemix/Packages/Kitura-net-1.4.3/Sources/CHTTPParser/include/module.modulemap","-I","/home/matthew/bluemix/Packages/Kitura-net-1.4.3/Sources/CHTTPParser/include","-Xcc","-I/usr/include","-L/usr/lib/x86_64-linux-gnu","-lssl","-lcrypto","-module-cache-path","/home/matthew/bluemix/.build/debug/ModuleCache"]
sources: ["/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/KituraRequest+Error.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/KituraRequest.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/URLEncoding.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/Encoding.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/JSONEncoding.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartEncoding.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Request/Request.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Request/Request+Parameters.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Request/Request+Method.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Request/Request+CompletionHandler.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/BodyPart.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/BodyPart+MimeTypeSubtypes.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/BodyBoundary.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/BodyPart+MimeType.swift","/home/matthew/bluemix/Packages/KituraRequest-0.5.0/Sources/KituraRequest/Encoding/MultipartFormData/KituraRequest+Random.swift"]
is-library: true
enable-whole-module-optimization: false
num-threads: "8"

It was trying to compile BodyPart+MimeTypeSubtypes.swift before BodyPart+MimeType.swift (which contains the MimeType extension to BodyPart), causing the error. I wondered if this was an annoying alphanumeric problem - the two file names are equal until comparing 'S' with '.' with 'S' coming first, so I renamed the file. Hey presto, compilation successful with BodyPart+MimeType.Subtypes.swift comping later in the source list than BodyPart+MimeType.swift.

### CODE REVIEW

**Comment by shmuelk** [comment]
While you seem to have fixed things on Linux you have broken them on macOS.

Did you test on macOS?

**Comment by mattcolegate** [comment]
I am unable to test on macOS as I have no access to a Mac environment.
I've no problem reverting the change but then that leaves me with the original problem.
I see the travis builds were passing before my change - am I missing some kind of build parameter or environment configuration?

**Comment by shmuelk** [comment]
I don't disagree with your problem it is failing for me as well.

My Linux is Ubuntu 16.04 with Swift 3.0.2. I believe on Travis we're using Ubuntu 14.04. Maybe that makes a difference.

**Comment by mattcolegate** [comment]
Can't be - I'm on Ubuntu 14.04 :-)

**Comment by naithar** [comment]
Could this be connected to: [SR-631](https://bugs.swift.org/browse/SR-631) which doesn't seem to be resolved.

**Comment by shmuelk** [comment]
It looks like it.

@mattcolegate After reviewing the JIRA entry that @naithar mentioned. I think the correct thing to do is to simply merge Sources/KituraRequest/Encoding/MultipartFormData/BodyPart+MimeType.swift and Sources/KituraRequest/Encoding/MultipartFormData/BodyPart+MimeTypeSubtypes.swift into one file.

Do you want to do it? Or should I close your PR and do it myself?

BTW Have you signed a [CLA](https://github.com/IBM-Swift/CLA)?

**Comment by mattcolegate** [comment]
Please close the PR and do it yourself, thank you!
I'm a member of Swift@IBM already, so I've done the CLA I think.

**Pull request closed without merging**
