### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mman**
This change allows ``Kitura-Request`` to coexist side by side in projects based on ``Kitura`` 2.x.

Tested in production using both swift 4.0.3 and swift 4.1.

Without this change ``swift package update`` in both swift 4.0.3 and swift 4.1 hangs failing to resolve dependencies.

### CODE REVIEW

**Comment by mman** [comment]
The reason why I'm still sticking to Kitura-Request is that SwiftyRequest is heavily based on URLSession which is still not completely finished on Linux and therefore can not be used in production.

Here are the issues that I'm currently hitting:

https://github.com/IBM-Swift/SwiftyRequest/issues/25
https://github.com/IBM-Swift/SwiftyRequest/issues/24

**Comment by ianpartridge** [comment]
Hi, I'll happily merge this but can you remove `Package.resolved`? Typically that wouldn't be checked in to version control.

**Comment by mman** [comment]
@ianpartridge Sure, it's gone now :) Thanks.

**Comment by ianpartridge** [comment]
Tagged as https://github.com/IBM-Swift-Sunset/Kitura-Request/releases/tag/0.10.0

**Pull request merged**
